include:
  - project: repositories/chipsalliance-ci-scripts
    file: i3c-core.yaml

stages:
  - prebuild
  - build
  - deploy

build_docs:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  image: debian:bookworm
  before_script:
    - apt-get update
    - apt-get install python3-venv python3-pip python3 -y
    - cd docs/
    - python3 -m venv .venv/
    - source .venv/bin/activate
    - pip3 install -r requirements.txt
  script:
    - cd docs/
    - source .venv/bin/activate
    - make html
    - tar cf $CI_DOCS_ARCHIVE -C build/html/ .
    - mv $CI_DOCS_ARCHIVE build ..
  artifacts:
    paths:
      - build
      - $CI_DOCS_ARCHIVE

deploy:
  image: $CI_DOCS_DOCKER_IMAGE
  dependencies: [build_docs]
  stage: deploy
  tags: [docs]
  variables:
    GIT_STRATEGY: none
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE
