stages:
  - build
  - deploy

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  image: debian:bookworm
  before_script:
    - apt-get update
    - apt-get install python3-venv python3-pip python3 -y
    - cd docs/
    - python3 -m venv .venv/
    - source .venv/bin/activate
    - pip3 install -r requirements.txt
  script:
    - cd docs/
    - source .venv/bin/activate
    - make html
    - tar cf $CI_DOCS_ARCHIVE -C build/html/ .
    - mv $CI_DOCS_ARCHIVE build ..
  artifacts:
    paths:
      - build
      - $CI_DOCS_ARCHIVE

deploy:
  variables:
    GIT_STRATEGY: none
  image: $CI_DOCS_DOCKER_IMAGE
  dependencies:
    - build
  stage: deploy
  tags: ['docs']
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE
