# SPDX-License-Identifier: Apache-2.0

# ============================================
# * WARNING: DO NOT USE: TEST CONFIGURATIONS *
# ============================================

ahb:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 128
  DctDepth: 128
  FrontendBusInterface: "AHB"
  FrontendBusAddrWidth: 18
  FrontendBusDataWidth: 64
  DisableInputFF: True

axi:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 128
  DctDepth: 128
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 12
  FrontendBusDataWidth: 32
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 8
  FrontendBusIdFiltering: False
  DisableInputFF: True

axi_id_filtering:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 128
  DctDepth: 128
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 12
  FrontendBusDataWidth: 32
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 8
  FrontendBusIdFiltering: True
  NumPrivIds: 4
  DisableInputFF: True

axi_ff:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 128
  DctDepth: 128
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 12
  FrontendBusDataWidth: 32
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 8
  FrontendBusIdFiltering: False
  DisableInputFF: False

invalid_missing_cmd_fifo_depth:
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 32
  DctDepth: 32
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 64
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 2
  FrontendBusIdFiltering: False
  DisableInputFF: False

invalid_too_many_args:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 64
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 2
  DisableInputFF: False
  FrontendBusIdFiltering: False
  AdditionalArg: "arg"

invalid_wrong_type:
  CmdFifoDepth: "This should be int"
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 64
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 2
  FrontendBusIdFiltering: False
  DisableInputFF: False

invalid_out_of_range:
  CmdFifoDepth: 64
  RxFifoDepth: 6666666666
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 64
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 2
  FrontendBusIdFiltering: False
  DisableInputFF: False

invalid_axi_missing_usr_width:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 64
  FrontendBusIdWidth: 2
  FrontendBusIdFiltering: False
  DisableInputFF: False

invalid_axi_missing_id_width:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 64
  FrontendBusUserWidth: 32
  FrontendBusIdFiltering: False
  DisableInputFF: False

invalid_axi_id_filtering_missing_num_priv_ids:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 128
  DctDepth: 128
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 12
  FrontendBusDataWidth: 32
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 8
  FrontendBusIdFiltering: True
  DisableInputFF: True

invalid_axi_id_filtering_off_num_priv_ids_defined:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 128
  DctDepth: 128
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 12
  FrontendBusDataWidth: 32
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 8
  FrontendBusIdFiltering: False
  NumPrivIds: 4
  DisableInputFF: True


invalid_unsupported_bus:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  FrontendBusInterface: "TileLink"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 64
  DisableInputFF: False

invalid_ahb_with_id_width:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  FrontendBusInterface: "AHB"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 64
  FrontendBusIdWidth: 2
  DisableInputFF: False

invalid_ahb_id_filtering_on:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  FrontendBusInterface: "AHB"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 64
  FrontendBusIdWidth: 2
  FrontendBusIdFiltering: True
  NumPrivIds: 4
  DisableInputFF: False

invalid_ahb_with_usr_width:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  FrontendBusInterface: "AHB"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 64
  FrontendBusUserWidth: 32
  DisableInputFF: False

invalid_ahb_with_axi_props:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  FrontendBusInterface: "AHB"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 64
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 2
  DisableInputFF: False

invalid_empty_arg:
  CmdFifoDepth:
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  FrontendBusInterface: "AHB"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 64
  DisableInputFF: False

edge_min_val:
  CmdFifoDepth: 64
  RxFifoDepth: 2
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  FrontendBusInterface: "AHB"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 64
  DisableInputFF: False

edge_one_less_than_max_val:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  FrontendBusInterface: "AHB"
  FrontendBusAddrWidth: 32
  FrontendBusDataWidth: 127
  DisableInputFF: False
